packages:
    - "Boilerplate/packages/*"
    - "Classic/packages/*"
    - "EffectTS/packages/*"

preferWorkspacePackages: true

linkWorkspacePackages: deep

minimumReleaseAge: 0

nodeLinker: hoisted

allowBuilds:
    puppeteer: true
    esbuild: true
