#!/usr/bin/env bash
# ============================================================
# Lychee link verification for the DeepSeek monorepo.
#
# Pass 1: the repo sources (the READMEs, the Documentation, the
#         package sources, the Site sources) - .lychee.toml.
# Pass 2: the built Site (Site/Target) - Site/lychee.toml.
# Pass 3: the generated API docs (Site/docs) - Site/lychee.toml.
#
# The passes compose lychee-report.md at the monorepo root: the
# methodology header, then each pass's summary + failures.
#
# Usage: pnpm lychee   (or: bash Maintain/Lychee.sh)
#
# lychee is required; install it first:
#   brew install lychee
#   (or: cargo install lychee)
# ============================================================
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v lychee >/dev/null 2>&1; then
	echo "lychee is not installed." >&2
	echo "Install it with: brew install lychee   (or: cargo install lychee)" >&2
	exit 1
fi

Work=$(mktemp -d)
trap 'rm -rf "$Work"' EXIT

Failed=0

echo "==> Pass 1: the repo sources (.lychee.toml)"
lychee --config .lychee.toml --output "$Work/Files.md" \
	"**/*.md" "**/*.ts" "**/*.tsx" "**/*.js" "**/*.json" || Failed=1

echo "==> Pass 2: the built Site (Site/lychee.toml)"
# The static build uses root-relative links; --root-dir resolves them
# against the build root (and the docs root for the generated API docs).
# The Site passes run when the Site tree is present (the local dev tree);
# the monorepo CI checkout carries no Site tree (the Site is its own
# repository) - the passes are skipped there, Pass 1 stays the CI gate.
if [ -d "Site" ]; then
	printf '# Pass 2 - the built Site (Site/lychee.toml)\n\n' > "$Work/Site.md"
	lychee --config Site/lychee.toml --root-dir Site/Target \
		--output "$Work/Site.md" Site/Target || Failed=1
	lychee --config Site/lychee.toml --root-dir Site/docs \
		--output "$Work/Docs.md" Site/docs || Failed=1
else
	echo "==> Pass 2: skipped - the Site tree is absent (the CI checkout)"
	printf '# Pass 2 - the built Site (Site/lychee.toml)\n\nSkipped: the Site tree is absent (the CI checkout - the Site is its own repository).\n\n' > "$Work/Site.md"
	printf '# Pass 3 - the generated API docs (Site/lychee.toml)\n\nSkipped: the Site tree is absent (the CI checkout - the Site is its own repository).\n\n' > "$Work/Docs.md"
fi

echo "==> Composing lychee-report.md"
{
	cat <<'HEADER'
# Lychee Link Verification Report - the DeepSeek monorepo

Generated by `pnpm lychee` (Maintain/Lychee.sh). Regenerate at any time; the
counts below reflect the last run.

## The methodology

Every external link in the monorepo's markdown, TypeScript/JavaScript sources,
and JSON manifests - the READMEs (root + every package + the Site), the
Documentation tree, the reports, and the Site's built HTML - is checked with
lychee. The two linking targets the family leans on (the DeepSeek Harness
`deepseek-ai/deepseek-harness` `tree/master` paths and the family's own
`PlayForm/DeepSeek` `tree/Current` paths, including the URL-registry reference
definitions at the root README's tail) are checked like any other link: no
allow-list for them, a dead target is a failure.

Two passes:

1. **The repo sources** (`.lychee.toml`): scans every file with the `.md`,
   `.ts`, `.tsx`, `.js`, `.json` extensions from the monorepo root. The
   dependencies (`node_modules`), the build output (`Target/`, `dist/`), the
   VCS internals (`.git`, `.astro`), the local smoke fixtures
   (`Test/fixtures`), and the lockfiles are excluded from the scan.
2. **The built Site** (`Site/lychee.toml`): scans the production build
   (`Site/Target`) and the generated API docs (`Site/docs`) - the artifacts the
   public actually fetches.

### The config rationale

- The schemes are `https`/`http`; `localhost`/`127.0.0.1` links are excluded
  (the dev-server URLs are environment-bound, not verifiable).
- `mailto:` and placeholder domains (`example.com`) are excluded.
- GitHub `#readme`/`#L<n>` anchors are excluded: GitHub hydrates them
  client-side, so lychee's static fetch always reports "Cannot find fragment"
  even when the link is valid. They are verified by hand instead.
- The request behavior: `get`, 30s timeout, 5 redirects max, 3 retries with a
  2s wait, concurrency 10, responses cached for a day so re-runs stay fast.
- Accepted status codes include the redirects and `429` - a rate-limited host
  must not report itself as a dead link; retry + cache absorb the rest.
- Fragment verification is on (`anchor-only`): a link's `#target` must exist
  on the fetched page.
- `.lycheeignore` carries the permanently unverifiable URLs (the shields.io
  badge images, the social/donation endpoints that block link checkers). Keep
  it minimal; a flaky URL goes there only after two consecutive runs fail it.

### The run instructions

```
brew install lychee        # once (or: cargo install lychee)
pnpm lychee                # both passes; writes lychee-report.md
```

The script exits non-zero when any pass reports errors, so it can gate CI.
A link that fails here is either fixed in place (the URL correction only -
the prose stays byte-identical) or moved to `.lycheeignore` with a reason.

HEADER
	printf '# Pass 1 - the repo sources (.lychee.toml)\n\n'
	cat "$Work/Files.md"
	printf '\n# Pass 2 - the built Site (Site/lychee.toml)\n\n'
	cat "$Work/Site.md"
	printf '\n# Pass 3 - the generated API docs (Site/lychee.toml)\n\n'
	cat "$Work/Docs.md"
} > lychee-report.md

echo "==> Done: lychee-report.md"
exit "$Failed"
